### ISSUE TITLE
训练效果不好

### ISSUE THREAD

**Issue by xiaolinstar** [Lornatang/SRCNN-PyTorch#6]
为什么我按照论文中的描述，训练的效果很差，还没有Bicubic的PSNR和SSIM高，请问你训练时候有遇到这样的问题吗？

**Comment by Taonanana** [comment]
我也训练效果很差

**Comment by Lornatang** [comment]
好的，过段时间我排查下这个问题，感谢对此项目的关注

**Comment by hashlure** [comment]
File "SRCNN-PyTorch-main\SRCNN-PyTorch-main\imgproc.py", line 502, in <module>
    scale_factor: float = 1.0) -> np.ndarray:
TypeError: 'type' object is not subscriptable报错

**Comment by zycomeon-boy** [comment]
/home/xujiajun/anaconda3/envs/Pytorch/bin/python /home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py 
Build SRCNN model successfully.
Load SRCNN model weights `/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/results/pretrained_models/srcnn_x4-T91-7c460643.pth.tar` successfully.
Processing `/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/data/X4/LR/1.png`...
sr_y_image shape: (128, 128, 1)
hr_cb_image shape: (512, 512)
hr_cr_image shape: (512, 512)
Traceback (most recent call last):
  File "/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py", line 109, in <module>
    main()
  File "/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py", line 89, in main
    sr_ycbcr_image = cv2.merge([sr_y_image, hr_cb_image, hr_cr_image])
cv2.error: OpenCV(4.8.0) /io/opencv/modules/core/src/merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'merge'


进程已结束,退出代码1

**Comment by Lornatang** [comment]
@zycomeon-boy 
try:
```python
hr_cb_image = np.expand_dims(hr_cb_image, axis=-1)
hr_cr_image = np.expand_dims(hr_cr_image, axis=-1)
```

**Comment by zycomeon-boy** [comment]
/home/xujiajun/anaconda3/envs/Pytorch/bin/python /home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py 
Build SRCNN model successfully.
Load SRCNN model weights `/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/results/pretrained_models/srcnn_x4-T91-7c460643.pth.tar` successfully.
Processing `/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/data/X4/LR/1.png`...
sr_y_image shape: (128, 128, 1)
hr_cb_image shape: (512, 512, 1)
hr_cr_image shape: (512, 512, 1)
Traceback (most recent call last):
  File "/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py", line 112, in <module>
    main()
  File "/home/xujiajun/桌面/zhaoyi/SRCNN-PyTorch-main/SRCNN-PyTorch-main/test.py", line 92, in main
    sr_ycbcr_image = cv2.merge([sr_y_image, hr_cb_image, hr_cr_image])
cv2.error: OpenCV(4.8.0) /io/opencv/modules/core/src/merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'merge'


进程已结束,退出代码1
问题依然存在
hr_ycbcr_image = imgproc.bgr2ycbcr(hr_image, False)
        _, hr_cb_image, hr_cr_image = cv2.split(hr_ycbcr_image)
        
        hr_cb_image = np.expand_dims(hr_cb_image, axis=-1)
        hr_cr_image = np.expand_dims(hr_cr_image, axis=-1)
        # Convert RGB channel image format data to Tensor channel image format data
        lr_y_tensor = imgproc.image2tensor(lr_y_image, False, True).unsqueeze_(0)
        hr_y_tensor = imgproc.image2tensor(hr_y_image, False, True).unsqueeze_(0)

**Comment by ningtai** [comment]
> File "SRCNN-PyTorch-main\SRCNN-PyTorch-main\imgproc.py", line 502, in scale_factor: float = 1.0) -> np.ndarray: TypeError: 'type' object is not subscriptable报错

python版本不对，tuple[int,int]改成tuple

**Comment by Odradecks** [comment]
> 为什么我按照论文中的描述，训练的效果很差，还没有Bicubic的PSNR和SSIM高，请问你训练时候有遇到这样的问题吗？
我也是，编解码出来的PSNR只有18

**Comment by Odradecks** [comment]
> 为什么我按照论文中的描述，训练的效果很差，还没有Bicubic的PSNR和SSIM高，请问你训练时候有遇到这样的问题吗？


我也是，编解码出来的PSNR只有18

**Comment by YAN287-hub** [comment]
> > 为什么我按照论文中的描述，训练的效果很差，还没有Bicubic的PSNR和SSIM高，请问你训练时候有遇到这样的问题吗？
> 
> 我也是，编解码出来的PSNR只有18

你好请问你解决了吗

**Comment by Lornatang** [comment]
建议关闭混合精度训练.

**Comment by YAN287-hub** [comment]
你好，我可以请教一些关于ESRGAN的问题吗，希望你可以为我解答，祝好
&nbsp;


Eve&nbsp;，小伤心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2026年3月11日(星期三) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: "Eve ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lornatang/SRCNN-PyTorch] 训练效果不好 (Issue #6)



Lornatang left a comment (Lornatang/SRCNN-PyTorch#6)
 
建议关闭混合精度训练.
